configfile: "config/config.yaml"


##NOTE: Remove ancient() in publication

# These are SLiM simulation parameters
MU = config["mu"]
CHROMOSOME = config["chromosome"]
ARM = config["arm"]
SLIM_SEED = config["slim_seed"]
DEMOGRAPHY = config["demography"]

# recombination position file - put it as "resources/recombination_map/recombination_position.csv"
RECOMBINATION_POSITION = config["recombination_position"]
# selection scaling parameter - this is set as a constant throughout the simulation
SELECTION_SCALING_PARAMETER = config["scaling_selection"]

# These are parameters for selecting individual IDs
YRI_NUMBER = config["YRI_number"]
CEU_NUMBER = config["CEU_number"]
CHB_NUMBER = config["CHB_number"]
JPT_NUMBER = config["JPT_number"]
INDIVIDUAL_SEED = config["individual_seed"]

# Recapitate parameters
RECAPITATE_SEED = config["recapitate_seed"]

# Neutral simulation parameters
NEUTRAL_MU = config["neutral_mu"]
NEUTRAL_SEED = config["neutral_seed"]

# VCZ generation parameter
MAF = config["maf"]

# Genetic value parameters
PROPORTION = config["proportion"]
GENETIC_SEED = config["genetic_seed"]

# FlashPCA parameter
FLASHPCA = config["flashpca"]

# 1000 Genomes vs MAF parameter
THOUSAND_YRI_NUM = config["thousand_yri_num"]
THOUSAND_CEU_NUM = config["thousand_ceu_num"]
THOUSAND_CHB_NUM = config["thousand_chb_num"]
THOUSAND_JPT_NUM = config["thousand_jpt_num"]

# 1000 Genomes parameter
THOUSAND_YRI_FOUNDER = config["thousand_yri_founder"]
THOUSAND_CEU_FOUNDER = config["thousand_ceu_founder"]
THOUSAND_CHB_FOUNDER = config["thousand_chb_founder"]
THOUSAND_JPT_FOUNDER = config["thousand_jpt_founder"]

# PopLDdecay parameter
POPLDDECAY = config["PopLDdecay"]

# GWAS parameter
PC1 = config["PC1"]
NUM_CEU_GWAS = config["num_ceu_gwas"]

# Recombination map directory
# Modify this string if you would ike to modify the location of recombination map
get_recombination_map = (
    "resources/recombination_map/HapMapII_GRCh38/genetic_map_Hg38_chr{chromosome}.txt"
)

output_pattern = (
    "slim_mu_{mu}_"
    "demography_{demography}_"
    "slim_seed_{slim_seed}_"
    "chr_{chromosome}{arm}"
)

# Folder pattern
folder_pattern = f"output/{output_pattern}"

# These parameters are used to sample tree sequence and select individual IDs
individual_id_pattern = (
    "yri_{yri}_ceu_{ceu}_chb_{chb}_jpt_{jpt}_individualseed_{individual_seed}"
)
# These parameters are used to sample tree sequence, select individual IDs and conduct recapitation
sample_tree_seq_pattern = f"{individual_id_pattern}_recap_seed_{{recapitate_seed}}"

final_ts_pattern = (
    f"{sample_tree_seq_pattern}_neutralmu_{{neutral_mu}}_neutralseed_{{neutral_seed}}"
)

vcz_pattern = f"{final_ts_pattern}_MAF_{{maf}}"

# These parameters are used to simulate genetic values of individuals
genetic_value_pattern = (
    f"{sample_tree_seq_pattern}_prop_{{proportion}}_genetic_seed_{{genetic_seed}}"
)

pca_output = expand(
    f"{folder_pattern}/plink_output/pca_output/pca_plot_{vcz_pattern}.pdf",
    mu=MU,
    demography=DEMOGRAPHY,
    slim_seed=SLIM_SEED,
    chromosome=CHROMOSOME,
    arm=ARM,
    yri=YRI_NUMBER,
    ceu=CEU_NUMBER,
    chb=CHB_NUMBER,
    jpt=JPT_NUMBER,
    individual_seed=INDIVIDUAL_SEED,
    recapitate_seed=RECAPITATE_SEED,
    neutral_mu=NEUTRAL_MU,
    neutral_seed=NEUTRAL_SEED,
    maf=MAF,
)

plink_bed = expand(
    f"{folder_pattern}/plink_output/plink_{vcz_pattern}.bed",
    mu=MU,
    demography=DEMOGRAPHY,
    slim_seed=SLIM_SEED,
    chromosome=CHROMOSOME,
    arm=ARM,
    yri=YRI_NUMBER,
    ceu=CEU_NUMBER,
    chb=CHB_NUMBER,
    jpt=JPT_NUMBER,
    individual_seed=INDIVIDUAL_SEED,
    recapitate_seed=RECAPITATE_SEED,
    neutral_mu=NEUTRAL_MU,
    neutral_seed=NEUTRAL_SEED,
    maf=MAF,
)

genetic_output = expand(
    f"{folder_pattern}/genetic_value_{genetic_value_pattern}.csv",
    mu=MU,
    demography=DEMOGRAPHY,
    slim_seed=SLIM_SEED,
    chromosome=CHROMOSOME,
    arm=ARM,
    yri=YRI_NUMBER,
    ceu=CEU_NUMBER,
    chb=CHB_NUMBER,
    jpt=JPT_NUMBER,
    individual_seed=INDIVIDUAL_SEED,
    recapitate_seed=RECAPITATE_SEED,
    proportion=PROPORTION,
    genetic_seed=GENETIC_SEED,
)

maf_plot_comparison = expand(
    f"{folder_pattern}/data_process/maf_plot_{final_ts_pattern}.pdf",
    mu=MU,
    demography=DEMOGRAPHY,
    slim_seed=SLIM_SEED,
    chromosome=CHROMOSOME,
    arm=ARM,
    yri=YRI_NUMBER,
    ceu=CEU_NUMBER,
    chb=CHB_NUMBER,
    jpt=JPT_NUMBER,
    individual_seed=INDIVIDUAL_SEED,
    recapitate_seed=RECAPITATE_SEED,
    neutral_mu=NEUTRAL_MU,
    neutral_seed=NEUTRAL_SEED,
)

lddecay_plot_comparison = expand(
    f"{folder_pattern}/data_process/ld_decay/ld_decay_plot_{final_ts_pattern}.pdf",
    mu=MU,
    demography=DEMOGRAPHY,
    slim_seed=SLIM_SEED,
    chromosome=CHROMOSOME,
    arm=ARM,
    yri=YRI_NUMBER,
    ceu=CEU_NUMBER,
    chb=CHB_NUMBER,
    jpt=JPT_NUMBER,
    individual_seed=INDIVIDUAL_SEED,
    recapitate_seed=RECAPITATE_SEED,
    neutral_mu=NEUTRAL_MU,
    neutral_seed=NEUTRAL_SEED,
)

ceu_ind_id_gwas = expand(
    f"{folder_pattern}/gwas_output/ceu_ind_id_{vcz_pattern}.txt",
    mu=MU,
    demography=DEMOGRAPHY,
    slim_seed=SLIM_SEED,
    chromosome=CHROMOSOME,
    arm=ARM,
    yri=YRI_NUMBER,
    ceu=CEU_NUMBER,
    chb=CHB_NUMBER,
    jpt=JPT_NUMBER,
    individual_seed=INDIVIDUAL_SEED,
    recapitate_seed=RECAPITATE_SEED,
    neutral_mu=NEUTRAL_MU,
    neutral_seed=NEUTRAL_SEED,
    maf=MAF,
)


rule all:
    input:
        plink_bed,
        genetic_output,


rule obtain_lddecay:
    input:
        lddecay_plot_comparison,


rule obtain_maf:
    input:
        maf_plot_comparison,


rule obtain_pca:
    input:
        pca_output,


rule obtain_ceu_gwas:
    input:
        ceu_ind_id_gwas,


rule generate_slim_script:
    input:
        demography=ancient(
            lambda wildcards: f"resources/demography/{wildcards.demography}.yaml"
        ),
        recombination_map_file=ancient(
            lambda wildcards: get_recombination_map.format(
                chromosome=wildcards.chromosome
            )
        ),
        position_file=ancient(RECOMBINATION_POSITION),
    output:
        slim_script=f"{folder_pattern}/slim_script.slim",
    log:
        f"logs/{folder_pattern}/slim_script.log",
    conda:
        "envs/simulation.yaml"
    params:
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
        mu=lambda wildcards: wildcards.mu,
        selection_scaling=SELECTION_SCALING_PARAMETER,
        slim_seed=lambda wildcards: wildcards.slim_seed,
    script:
        "scripts/generate_slim_script.py"


rule slim_underdominance:
    input:
        f"{folder_pattern}/slim_script.slim",
    output:
        f"{folder_pattern}/slim_allele.tree",
    log:
        f"logs/{folder_pattern}/slim_underdominance.log",
    conda:
        "envs/simulation.yaml"
    resources:
        mem_mb=320000,
    shell:
        "slim -d 'tree_filename=\"{output}\"' {input} > {log}"


rule sample_individuals:
    input:
        ts=f"{folder_pattern}/slim_allele.tree",
    output:
        individual_id=f"{folder_pattern}/individual_id_{individual_id_pattern}.csv",
    log:
        f"logs/{folder_pattern}/sample_individuals_{individual_id_pattern}.log",
    conda:
        "envs/simulation.yaml"
    params:
        yri_number=lambda wildcards: wildcards.yri,
        ceu_number=lambda wildcards: wildcards.ceu,
        chb_number=lambda wildcards: wildcards.chb,
        jpt_number=lambda wildcards: wildcards.jpt,
        individual_seed=lambda wildcards: wildcards.individual_seed,
    script:
        "scripts/sample_individuals.py"


rule recapitate_sample_individuals:
    input:
        ts=f"{folder_pattern}/slim_allele.tree",
        individual_id=f"{folder_pattern}/individual_id_{individual_id_pattern}.csv",
        demography=ancient(
            lambda wildcards: f"resources/demography/{wildcards.demography}.yaml"
        ),
        recombination_map_file=ancient(
            lambda wildcards: get_recombination_map.format(
                chromosome=wildcards.chromosome
            )
        ),
        position_file=ancient(RECOMBINATION_POSITION),
    output:
        ts=f"{folder_pattern}/subset_nucleotide_{sample_tree_seq_pattern}.tree",
    log:
        f"logs/{folder_pattern}/racapitate_sample_individuals_{sample_tree_seq_pattern}.log",
    conda:
        "envs/simulation.yaml"
    params:
        chromosome=lambda wildcards: wildcards.chromosome,
        arm=lambda wildcards: wildcards.arm,
        recapitate_seed=lambda wildcards: wildcards.recapitate_seed,
    script:
        "scripts/recapitate_sample_individuals.py"


rule generate_neutral_mutation:
    input:
        ts=f"{folder_pattern}/subset_nucleotide_{sample_tree_seq_pattern}.tree",
    output:
        ts=f"{folder_pattern}/final_output_{final_ts_pattern}.tree.tsz",
    log:
        f"logs/{folder_pattern}/generate_neutral_mutation_{final_ts_pattern}.log",
    conda:
        "envs/simulation.yaml"
    params:
        neutral_mu=lambda wildcards: wildcards.neutral_mu,
        neutral_seed=lambda wildcards: wildcards.neutral_seed,
    script:
        "scripts/generate_neutral_mutation.py"


rule generate_vcz:
    input:
        ts=f"{folder_pattern}/final_output_{final_ts_pattern}.tree.tsz",
        individual_id=f"{folder_pattern}/individual_id_{individual_id_pattern}.csv",
    output:
        vcz=directory(f"{folder_pattern}/{vcz_pattern}.vcz"),
    log:
        f"logs/{folder_pattern}/generate_vcz_{vcz_pattern}.log",
    conda:
        "envs/simulation.yaml"
    threads: 2
    resources:
        cpus_per_task=2,
        mem_mb=320000,
    params:
        maf=lambda wildcards: wildcards.maf,
        chromosome=lambda wildcards: wildcards.chromosome,
    script:
        "scripts/generate_vcz.py"


rule generate_plink:
    input:
        f"{folder_pattern}/{vcz_pattern}.vcz",
    output:
        bed=f"{folder_pattern}/plink_output/plink_{vcz_pattern}.bed",
        bim=f"{folder_pattern}/plink_output/plink_{vcz_pattern}.bim",
        fam=f"{folder_pattern}/plink_output/plink_{vcz_pattern}.fam",
    log:
        f"logs/{folder_pattern}/generate_plink_{vcz_pattern}.log",
    conda:
        "envs/simulation.yaml"
    params:
        outprefix=lambda wildcards, output: output.bed[:-4],
    shell:
        "vcztools view-plink {input} -M 2 -o {params.outprefix}"


rule genetic_value_simulation:
    input:
        ts=f"{folder_pattern}/subset_nucleotide_{sample_tree_seq_pattern}.tree",
    output:
        genetic_df=f"{folder_pattern}/genetic_value_{genetic_value_pattern}.csv",
        mutation_df=f"{folder_pattern}/mutation_{genetic_value_pattern}.csv",
    log:
        f"logs/{folder_pattern}/genetic_value_simulation_{genetic_value_pattern}.log",
    conda:
        "envs/simulation.yaml"
    params:
        proportion=lambda wildcards: wildcards.proportion,
        genetic_seed=lambda wildcards: wildcards.genetic_seed,
        selection_scaling=SELECTION_SCALING_PARAMETER,
    script:
        "scripts/genetic_value_simulation.py"


rule process_plink:
    input:
        bed=f"{folder_pattern}/plink_output/plink_{vcz_pattern}.bed",
        bim=f"{folder_pattern}/plink_output/plink_{vcz_pattern}.bim",
        fam=f"{folder_pattern}/plink_output/plink_{vcz_pattern}.fam",
    output:
        bed=f"{folder_pattern}/plink_output/plink_gwas_{vcz_pattern}.bed",
        bim=f"{folder_pattern}/plink_output/plink_gwas_{vcz_pattern}.bim",
        fam=f"{folder_pattern}/plink_output/plink_gwas_{vcz_pattern}.fam",
    log:
        f"logs/{folder_pattern}/process_plink_{vcz_pattern}.log",
    conda:
        "envs/plink.yaml"
    params:
        outprefix=lambda wildcards, output: output.bed[:-4],
        inprefix=lambda wildcards, input: input.bed[:-4],
    shell:
        """
        plink2 \
            --bfile {params.inprefix} \
            --set-all-var-ids @:#:\\$r:\\$a \
            --maf 0.01 \
            --make-bed \
            --out {params.outprefix} >{log}
        """


rule variant_pruning:
    input:
        bed=f"{folder_pattern}/plink_output/plink_gwas_{vcz_pattern}.bed",
        bim=f"{folder_pattern}/plink_output/plink_gwas_{vcz_pattern}.bim",
        fam=f"{folder_pattern}/plink_output/plink_gwas_{vcz_pattern}.fam",
    output:
        bed=f"{folder_pattern}/plink_output/variant_pruning/plink_{vcz_pattern}.bed",
        bim=f"{folder_pattern}/plink_output/variant_pruning/plink_{vcz_pattern}.bim",
        fam=f"{folder_pattern}/plink_output/variant_pruning/plink_{vcz_pattern}.fam",
    log:
        f"logs/{folder_pattern}/variant_pruning_{vcz_pattern}.log",
    conda:
        "envs/plink.yaml"
    params:
        outprefix=lambda wildcards, output: output.bed[:-4],
        inprefix=lambda wildcards, input: input.bed[:-4],
    shell:
        """
        plink2 \
            --bfile {params.inprefix} \
            --out {params.outprefix} \
            --indep-pairwise 1000 80 0.1 >{log}
        plink2 \
            --bfile {params.inprefix} \
            --extract {params.outprefix}.prune.in \
            --make-bed \
            --out {params.outprefix} >>{log}
        """


rule run_flashpca:
    input:
        bed=f"{folder_pattern}/plink_output/variant_pruning/plink_{vcz_pattern}.bed",
        bim=f"{folder_pattern}/plink_output/variant_pruning/plink_{vcz_pattern}.bim",
        fam=f"{folder_pattern}/plink_output/variant_pruning/plink_{vcz_pattern}.fam",
    output:
        eigenvectors=f"{folder_pattern}/pca_output/eigenvectors_{vcz_pattern}.txt",
        pcs=f"{folder_pattern}/pca_output/pcs_{vcz_pattern}.txt",
        eigenvalues=f"{folder_pattern}/pca_output/eigenvalues_{vcz_pattern}.txt",
        pve=f"{folder_pattern}/pca_output/pve_{vcz_pattern}.txt",
    log:
        f"logs/{folder_pattern}/run_flashpca_{vcz_pattern}.log",
    conda:
        "envs/plink.yaml"
    resources:
        mem_mb=10000,
    params:
        flashpca=FLASHPCA,
        inprefix=lambda wildcards, input: input.bed[:-4],
    shell:
        """
        {params.flashpca} \
            --bfile {params.inprefix} \
            --outpc {output.pcs} \
            --outvec {output.eigenvectors} \
            --outval {output.eigenvalues} \
            --outpve {output.pve} >{log}
        """


rule plot_pca_result:
    input:
        pcs=f"{folder_pattern}/plink_output/pca_output/pcs_{vcz_pattern}.txt",
    output:
        plot=f"{folder_pattern}/plink_output/pca_output/pca_plot_{vcz_pattern}.pdf",
    log:
        f"logs/{folder_pattern}/plot_pca_result_{vcz_pattern}.log",
    conda:
        "envs/plot.yaml"
    resources:
        mem_mb=20000,
    params:
        chromosome=lambda wildcards: wildcards.chromosome,
        arm=lambda wildcards: wildcards.arm,
    script:
        "scripts/plot_pca.py"


rule obtain_sample_thousand_maf:
    input:
        ts=f"{folder_pattern}/final_output_{final_ts_pattern}.tree.tsz",
        individual_id=f"{folder_pattern}/individual_id_{individual_id_pattern}.csv",
    output:
        yri_maf=f"{folder_pattern}/data_process/yri_sim_maf_{final_ts_pattern}.csv",
        ceu_maf=f"{folder_pattern}/data_process/ceu_sim_maf_{final_ts_pattern}.csv",
        chb_maf=f"{folder_pattern}/data_process/chb_sim_maf_{final_ts_pattern}.csv",
        jpt_maf=f"{folder_pattern}/data_process/jpt_sim_maf_{final_ts_pattern}.csv",
    log:
        f"logs/{folder_pattern}/obtain_sample_thousand_maf_{final_ts_pattern}.log",
    conda:
        "envs/simulation.yaml"
    resources:
        mem_mb=100000,
    params:
        yri_number=THOUSAND_YRI_NUM,
        ceu_number=THOUSAND_CEU_NUM,
        chb_number=THOUSAND_CHB_NUM,
        jpt_number=THOUSAND_JPT_NUM,
        individual_seed=lambda wildcards: wildcards.individual_seed,
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
    script:
        "scripts/obtain_maf.py"


get_thousand_genomes = "resources/1000genomes/1kGP_high_coverage_Illumina.chr{chromosome}.filtered.SNV_INDEL_SV_phased_panel.vcf.gz"


rule obtain_thousand_maf:
    input:
        position_file=ancient(RECOMBINATION_POSITION),
        thousand_genomes=ancient(
            lambda wildcards: get_thousand_genomes.format(
                chromosome=wildcards.chromosome
            )
        ),
    output:
        yri_maf=f"{folder_pattern}/data_process/yri_thousand_maf_{final_ts_pattern}.txt",
        ceu_maf=f"{folder_pattern}/data_process/ceu_thousand_maf_{final_ts_pattern}.txt",
        chb_maf=f"{folder_pattern}/data_process/chb_thousand_maf_{final_ts_pattern}.txt",
        jpt_maf=f"{folder_pattern}/data_process/jpt_thousand_maf_{final_ts_pattern}.txt",
    log:
        f"logs/{folder_pattern}/obtain_thousand_maf_{final_ts_pattern}.log",
    conda:
        "envs/bcftools.yaml"
    resources:
        mem_mb=10000,
    params:
        yri_founder=THOUSAND_YRI_FOUNDER,
        ceu_founder=THOUSAND_CEU_FOUNDER,
        chb_founder=THOUSAND_CHB_FOUNDER,
        jpt_founder=THOUSAND_JPT_FOUNDER,
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
    script:
        "scripts/obtain_thousand_maf.py"


rule plot_maf:
    input:
        yri_thousand_maf=f"{folder_pattern}/data_process/yri_thousand_maf_{final_ts_pattern}.txt",
        ceu_thousand_maf=f"{folder_pattern}/data_process/ceu_thousand_maf_{final_ts_pattern}.txt",
        chb_thousand_maf=f"{folder_pattern}/data_process/chb_thousand_maf_{final_ts_pattern}.txt",
        jpt_thousand_maf=f"{folder_pattern}/data_process/jpt_thousand_maf_{final_ts_pattern}.txt",
        yri_sim_maf=f"{folder_pattern}/data_process/yri_sim_maf_{final_ts_pattern}.csv",
        ceu_sim_maf=f"{folder_pattern}/data_process/ceu_sim_maf_{final_ts_pattern}.csv",
        chb_sim_maf=f"{folder_pattern}/data_process/chb_sim_maf_{final_ts_pattern}.csv",
        jpt_sim_maf=f"{folder_pattern}/data_process/jpt_sim_maf_{final_ts_pattern}.csv",
    output:
        plot=f"{folder_pattern}/data_process/maf_plot_{final_ts_pattern}.pdf",
    log:
        f"logs/{folder_pattern}/plot_maf_{final_ts_pattern}.log",
    conda:
        "envs/plot.yaml"
    params:
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
    script:
        "scripts/plot_maf.py"


rule obtain_thousand_ld_decay:
    input:
        position_file=ancient(RECOMBINATION_POSITION),
        thousand_genomes=ancient(
            lambda wildcards: get_thousand_genomes.format(
                chromosome=wildcards.chromosome
            )
        ),
    output:
        yri_ld_decay=f"{folder_pattern}/data_process/ld_decay/yri_thousand_ld_decay_{final_ts_pattern}.stat.gz",
        ceu_ld_decay=f"{folder_pattern}/data_process/ld_decay/ceu_thousand_ld_decay_{final_ts_pattern}.stat.gz",
        chb_ld_decay=f"{folder_pattern}/data_process/ld_decay/chb_thousand_ld_decay_{final_ts_pattern}.stat.gz",
        jpt_ld_decay=f"{folder_pattern}/data_process/ld_decay/jpt_thousand_ld_decay_{final_ts_pattern}.stat.gz",
    log:
        f"logs/{folder_pattern}/obtain_thousand_ld_decay_{final_ts_pattern}.log",
    conda:
        "envs/bcftools.yaml"
    resources:
        mem_mb=10000,
    params:
        yri_founder=THOUSAND_YRI_FOUNDER,
        ceu_founder=THOUSAND_CEU_FOUNDER,
        chb_founder=THOUSAND_CHB_FOUNDER,
        jpt_founder=THOUSAND_JPT_FOUNDER,
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
        poplddecay=POPLDDECAY,
    script:
        "scripts/obtain_thousand_lddecay.py"


rule obtain_sim_ld_decay:
    input:
        ts=f"{folder_pattern}/final_output_{final_ts_pattern}.tree.tsz",
        individual_id=f"{folder_pattern}/individual_id_{individual_id_pattern}.csv",
    output:
        yri_ld_decay=f"{folder_pattern}/data_process/ld_decay/yri_sim_ld_decay_{final_ts_pattern}.stat.gz",
        ceu_ld_decay=f"{folder_pattern}/data_process/ld_decay/ceu_sim_ld_decay_{final_ts_pattern}.stat.gz",
        chb_ld_decay=f"{folder_pattern}/data_process/ld_decay/chb_sim_ld_decay_{final_ts_pattern}.stat.gz",
        jpt_ld_decay=f"{folder_pattern}/data_process/ld_decay/jpt_sim_ld_decay_{final_ts_pattern}.stat.gz",
    log:
        f"logs/{folder_pattern}/obtain_sim_ld_decay_{final_ts_pattern}.log",
    conda:
        "envs/simulation.yaml"
    resources:
        mem_mb=100000,
    params:
        yri_number=THOUSAND_YRI_NUM,
        ceu_number=THOUSAND_CEU_NUM,
        chb_number=THOUSAND_CHB_NUM,
        jpt_number=THOUSAND_JPT_NUM,
        individual_seed=lambda wildcards: wildcards.individual_seed,
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
        poplddecay=POPLDDECAY,
    script:
        "scripts/obtain_lddecay.py"


rule plot_ld_decay:
    input:
        yri_thousand_ld_decay=f"{folder_pattern}/data_process/ld_decay/yri_thousand_ld_decay_{final_ts_pattern}.stat.gz",
        ceu_thousand_ld_decay=f"{folder_pattern}/data_process/ld_decay/ceu_thousand_ld_decay_{final_ts_pattern}.stat.gz",
        chb_thousand_ld_decay=f"{folder_pattern}/data_process/ld_decay/chb_thousand_ld_decay_{final_ts_pattern}.stat.gz",
        jpt_thousand_ld_decay=f"{folder_pattern}/data_process/ld_decay/jpt_thousand_ld_decay_{final_ts_pattern}.stat.gz",
        yri_sim_ld_decay=f"{folder_pattern}/data_process/ld_decay/yri_sim_ld_decay_{final_ts_pattern}.stat.gz",
        ceu_sim_ld_decay=f"{folder_pattern}/data_process/ld_decay/ceu_sim_ld_decay_{final_ts_pattern}.stat.gz",
        chb_sim_ld_decay=f"{folder_pattern}/data_process/ld_decay/chb_sim_ld_decay_{final_ts_pattern}.stat.gz",
        jpt_sim_ld_decay=f"{folder_pattern}/data_process/ld_decay/jpt_sim_ld_decay_{final_ts_pattern}.stat.gz",
    output:
        plot=f"{folder_pattern}/data_process/ld_decay/ld_decay_plot_{final_ts_pattern}.pdf",
    log:
        f"logs/{folder_pattern}/plot_maf_{final_ts_pattern}.log",
    conda:
        "envs/plot.yaml"
    params:
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
    script:
        "scripts/plot_lddecay.py"


rule obtain_ceu_ind_id:
    input:
        pcs=f"{folder_pattern}/pca_output/pcs_{vcz_pattern}.txt",
        genetic_df=f"{folder_pattern}/genetic_value_{genetic_value_pattern}.csv",
    output:
        individual_id=f"{folder_pattern}/gwas_output/ceu_ind_id_{vcz_pattern}.txt",
        genetic_value=f"{folder_pattern}/gwas_output/ceu_genetic_value_{genetic_value_pattern}.csv",
    log:
        f"logs/{folder_pattern}/obtain_ceu_ind_id_{vcz_pattern}_{genetic_value_pattern}.log",
    conda:
        "envs/simulation.yaml"
    params:
        individual_seed=lambda wildcards: wildcards.individual_seed,
        arm=lambda wildcards: wildcards.arm,
        chromosome=lambda wildcards: wildcards.chromosome,
        pc1=PC1,
        num_ceu_gwas=NUM_CEU_GWAS,
    script:
        "scripts/obtain_ceu_ind.py"
