name: Snakemake

on:
  [pull_request, push]

jobs:
  Snakemake-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        uses: snakemake/snakemake-github-action@v2
        with:
          directory: ".test"
          snakefile: "workflow/Snakefile"
          args: "--lint"